name: pdh
channels:
  - anaconda
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_kmp_llvm
  - alsa-lib=1.2.8=h166bdaf_0
  - aom=3.5.0=h27087fc_0
  - asgiref=3.6.0=pyhd8ed1ab_0
  - asttokens=2.0.5=pyhd3eb1b0_0
  - attr=2.5.1=h166bdaf_1
  - backcall=0.2.0=pyhd3eb1b0_0
  - backports.zoneinfo=0.2.1=py39hf3d152e_7
  - blas=2.106=mkl
  - brotlipy=0.7.0=py39hb9d737c_1005
  - bzip2=1.0.8=h7f98852_4
  - c-ares=1.18.1=h7f98852_0
  - ca-certificates=2023.01.10=h06a4308_0
  - cairo=1.16.0=ha61ee94_1014
  - certifi=2022.12.7=py39h06a4308_0
  - cffi=1.15.1=py39he91dace_3
  - charset-normalizer=2.1.1=pyhd8ed1ab_0
  - comm=0.1.2=py39h06a4308_0
  - cpuonly=2.0=0
  - cryptography=38.0.4=py39hd97740a_0
  - dbus=1.13.6=h5008d03_3
  - debugpy=1.5.1=py39h295c915_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - django=4.1.7=pyhd8ed1ab_0
  - djangorestframework=3.14.0=pyhd8ed1ab_0
  - entrypoints=0.4=py39h06a4308_0
  - executing=0.8.3=pyhd3eb1b0_0
  - expat=2.5.0=h27087fc_0
  - ffmpeg=5.1.2=gpl_h8dda1f0_106
  - fftw=3.3.10=nompi_hf0379b8_106
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=hab24e00_0
  - fontconfig=2.14.2=h14ed4e7_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - freeglut=3.2.2=h9c3ff4c_1
  - freetype=2.12.1=hca18f0e_1
  - gettext=0.21.1=h27087fc_0
  - glib=2.74.1=h6239696_1
  - glib-tools=2.74.1=h6239696_1
  - gmp=6.2.1=h58526e2_0
  - gnutls=3.7.8=hf3e180e_0
  - graphite2=1.3.13=h58526e2_1001
  - gst-plugins-base=1.21.3=h4243ec0_1
  - gstreamer=1.21.3=h25f0c4b_1
  - harfbuzz=6.0.0=h8e241bc_0
  - hdf5=1.14.0=nompi_h5231ba7_102
  - icu=70.1=h27087fc_0
  - idna=3.4=pyhd8ed1ab_0
  - ipykernel=6.19.2=py39hb070fc8_0
  - ipython=8.10.0=py39h06a4308_0
  - jack=1.9.22=h11f4161_0
  - jasper=2.0.33=h0ff4b12_1
  - jedi=0.18.1=py39h06a4308_1
  - jpeg=9e=h0b41bf4_3
  - jupyter_client=7.4.9=py39h06a4308_0
  - jupyter_core=5.2.0=py39h06a4308_0
  - keyutils=1.6.1=h166bdaf_0
  - krb5=1.19.3=h3790be6_0
  - lame=3.100=h166bdaf_1003
  - lcms2=2.14=hfd0df8a_1
  - ld_impl_linux-64=2.40=h41732ed_0
  - lerc=4.0.0=h27087fc_0
  - libaec=1.0.6=hcb278e6_1
  - libblas=3.9.0=6_mkl
  - libcap=2.66=ha37c62d_0
  - libcblas=3.9.0=6_mkl
  - libclang=15.0.7=default_had23c3d_1
  - libclang13=15.0.7=default_h3e3d535_1
  - libcups=2.3.3=h3e49a29_2
  - libcurl=7.87.0=h91b91d3_0
  - libdb=6.2.32=h9c3ff4c_0
  - libdeflate=1.17=h0b41bf4_0
  - libdrm=2.4.114=h166bdaf_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=h516909a_1
  - libevent=2.1.10=h9b69904_4
  - libffi=3.4.2=h7f98852_5
  - libflac=1.4.2=h27087fc_0
  - libgcc-ng=12.2.0=h65d4601_19
  - libgfortran-ng=12.2.0=h69a702a_19
  - libgfortran5=12.2.0=h337968e_19
  - libglib=2.74.1=h606061b_1
  - libglu=9.0.0=he1b5a44_1001
  - libiconv=1.17=h166bdaf_0
  - libidn2=2.3.4=h166bdaf_0
  - liblapack=3.9.0=6_mkl
  - liblapacke=3.9.0=6_mkl
  - libllvm15=15.0.7=hadd5161_0
  - libnghttp2=1.46.0=hce63b2e_0
  - libogg=1.3.4=h7f98852_1
  - libopencv=4.7.0=py39h2ca4621_1
  - libopus=1.3.1=h7f98852_1
  - libpciaccess=0.17=h166bdaf_0
  - libpng=1.6.39=h753d276_0
  - libpq=14.5=h72a31a5_3
  - libprotobuf=3.21.12=h3eb15da_0
  - libsndfile=1.1.0=hcb278e6_1
  - libsodium=1.0.18=h7b6447c_0
  - libsqlite=3.40.0=h753d276_0
  - libssh2=1.10.0=haa6b8db_3
  - libstdcxx-ng=12.2.0=h46fd767_19
  - libtasn1=4.19.0=h166bdaf_0
  - libtiff=4.5.0=h6adf6a1_2
  - libtool=2.4.7=h27087fc_0
  - libudev1=253=h0b41bf4_0
  - libunistring=0.9.10=h7f98852_0
  - libuuid=2.32.1=h7f98852_1000
  - libva=2.17.0=h0b41bf4_0
  - libvorbis=1.3.7=h9c3ff4c_0
  - libvpx=1.11.0=h9c3ff4c_3
  - libwebp-base=1.2.4=h166bdaf_0
  - libxcb=1.13=h7f98852_1004
  - libxkbcommon=1.5.0=h79f4944_0
  - libxml2=2.10.3=h7463322_0
  - libzlib=1.2.13=h166bdaf_4
  - llvm-openmp=15.0.7=h0cdce71_0
  - matplotlib-inline=0.1.6=py39h06a4308_0
  - mkl=2020.4=h726a3e6_304
  - mpg123=1.31.2=hcb278e6_0
  - mysql-common=8.0.32=h14678bc_0
  - mysql-libs=8.0.32=h54cf53e_0
  - ncurses=6.3=h27087fc_1
  - nest-asyncio=1.5.6=py39h06a4308_0
  - nettle=3.8.1=hc379101_1
  - nspr=4.35=h27087fc_0
  - nss=3.88=he45b914_0
  - numpy=1.24.2=py39h7360e5f_0
  - opencv=4.7.0=py39hf3d152e_1
  - openh264=2.3.1=hcb278e6_2
  - openjpeg=2.5.0=hfec8fc6_2
  - openssl=1.1.1t=h7f8727e_0
  - p11-kit=0.24.1=hc5aa10d_0
  - packaging=22.0=py39h06a4308_0
  - parso=0.8.3=pyhd3eb1b0_0
  - pcre2=10.40=hc3806b6_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=9.4.0=py39h2320bf1_1
  - pip=23.0.1=pyhd8ed1ab_0
  - pixman=0.40.0=h36c2ea0_0
  - platformdirs=2.5.2=py39h06a4308_0
  - prompt-toolkit=3.0.36=py39h06a4308_0
  - psutil=5.9.0=py39h5eee18b_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pulseaudio=14.0=h0d2025b_11
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - py-opencv=4.7.0=py39hcca971b_1
  - pycparser=2.21=pyhd8ed1ab_0
  - pygments=2.11.2=pyhd3eb1b0_0
  - pyopenssl=23.0.0=pyhd8ed1ab_0
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.9.16=h7a1cb2a_0
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python_abi=3.9=2_cp39
  - pytorch=1.13.1=py3.9_cpu_0
  - pytorch-mutex=1.0=cpu
  - pytz=2022.7.1=pyhd8ed1ab_0
  - pyzmq=23.2.0=py39h6a678d5_0
  - qt-main=5.15.6=hd477bba_1
  - readline=8.1.2=h0f457ee_0
  - requests=2.28.2=pyhd8ed1ab_0
  - setuptools=67.4.0=pyhd8ed1ab_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.40.1=h5082296_0
  - sqlparse=0.4.3=pyhd8ed1ab_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - svt-av1=1.4.1=hcb278e6_0
  - tk=8.6.12=h27826a3_0
  - torchaudio=0.13.1=py39_cpu
  - torchvision=0.14.1=py39_cpu
  - tornado=6.2=py39h5eee18b_0
  - traitlets=5.7.1=py39h06a4308_0
  - typing_extensions=4.4.0=pyha770c72_0
  - tzdata=2022g=h191b570_0
  - urllib3=1.26.14=pyhd8ed1ab_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - wheel=0.38.4=pyhd8ed1ab_0
  - x264=1!164.3095=h166bdaf_2
  - x265=3.5=h924138e_3
  - xcb-util=0.4.0=h166bdaf_0
  - xcb-util-image=0.4.0=h166bdaf_0
  - xcb-util-keysyms=0.4.0=h166bdaf_0
  - xcb-util-renderutil=0.3.9=h166bdaf_0
  - xcb-util-wm=0.4.1=h166bdaf_0
  - xorg-fixesproto=5.0=h7f98852_1002
  - xorg-inputproto=2.3.2=h7f98852_1002
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.0.10=h7f98852_0
  - xorg-libsm=1.2.3=hd9c2040_1000
  - xorg-libx11=1.8.4=h0b41bf4_0
  - xorg-libxau=1.0.9=h7f98852_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-libxext=1.3.4=h0b41bf4_2
  - xorg-libxfixes=5.0.3=h7f98852_1004
  - xorg-libxi=1.7.10=h7f98852_0
  - xorg-libxrender=0.9.10=h7f98852_1003
  - xorg-renderproto=0.11.1=h7f98852_1002
  - xorg-xextproto=7.3.0=h0b41bf4_1003
  - xorg-xproto=7.0.31=h7f98852_1007
  - xz=5.2.10=h5eee18b_1
  - zeromq=4.3.4=h2531618_0
  - zlib=1.2.13=h166bdaf_4
  - zstd=1.5.2=h3eb15da_6
prefix: /home/newton/anaconda3/envs/pdh
